### ISSUE TITLE
Further improve shot detection

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#107]
We need testcase support for improving shot detection:
1. (DONE) Record the video stream in ShootOFF
2. (DONE) Replay saved video streams in ShootOFF
3. (DONE) Basic testcase support for checking the results of shot detection during video replays
4. Any other diagnostic displays that will help us

Our problem with shot detection is that bright areas of the screen are now ignored by our bloom filter.
1. We need to stop camera auto brightness detection, or account for it somehow.  Ideally, we turn down the camera brightness until no pixel (other than random noise) is bright.
2. We need to average the brightness of the screen.  I think this needs to be done using the bloom filter data.  If a given pixel is consistently “bright” it should be stepped down until it no longer triggers on bright.  This is a balancing act, of course.  If it stops being bright it needs to stop being adjusted.
3. Leverage our bloom filter data for more, right now we have more data on noise than we actually use.

**Comment by phrack** [comment]
OK, if you are in debug mode you can now record a feed by right clicking it and hitting "Start Recording". This will output a debug message like:

[JavaFX Application Thread] DEBUG com.shootoff.camera.CameraManager - Writing Video Feed To: /home/phrack/ShootOFF/Default.mp4

To stop recording either right click the feed again and hit "Stop Recording" or just close ShootOFF.

I am not planning for this to ever be exposed outside of debug mode. If we need to record in the future we will indirectly expose it some other way (e.g. starting some kind of training session will start recording).

**Comment by phrack** [comment]
PS. The codec used is h264 for now. This is the same one used by YouTube. I chose it because it gets reasonably small files with basically no quality loss (for testing, we need the image to be true).

**Comment by phrack** [comment]
OK, you can use videos recorded in prior ShootOFF sessions in unit tests now and ShootOFF will behave like a user was running that exact same session again (assuming default configuration!). 

Any unit test using a video should appear in TestCameraManager. There is one example test in there of a video I took with two shots and no interference (i.e. a very easy case). 

This generally should not be an issue, but if you are recording a video to replay in a unit test, you  have to be sure there is enough of a gap at the beginning of the video before any shots happen to initialize the bloom filter. If you start shooting right away when you start recording because the bloom filter was already initialized in that session, you're going to wonder why shots are disappering in your unit test.

**Comment by phrack** [comment]
This issue is closed because #115 and #116 are more specific items for the points that have not yet been addressed in this issue.
