### ISSUE TITLE
Turn off shot detection during projector calibration and turn on calibration when projector arena opens

### ISSUE THREAD

**Issue by phrack** [phrack/ShootOFF#121]
The window chroming and letters can look like a shot while people are moving things around and getting set up. We can't trivially filter this out because we have no idea what their chroming colors will be and filters catching up isn't instant if a window moves on the projection a bunch.

Show the user a message on each feed saying that shot detection is disabled for calibration.

Ensure shot calibration is properly ended if the projector arena is closed during the process.

**Comment by cbdmaul** [comment]
I agree with the changes.

I suggest that the message be a bit more informative, something like:

"PROJECTION AREA

Place this window in your projector output,
and press F11 to full screen the window.

Shot detection is disabled until calibration is complete"

I know we'll want to refactor the usability anyway, but since you are modifying the message, it's an easy thing to do to make it slightly better.
