### ISSUE TITLE
Major frame corruption issue

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#386]
Arena masking is actually really close.  I've run into a major issue with frame corruption that is the real culprit of issues right now.

I attached an example.  Look around the edge of the red.  I am not (intentionally) changing those pixels.  There is corruption happening somewhere and it is in everything.  Even the test cases I made for arena masking have it.  It is not coming off my cam this way, at least watching the stream in VLC doesn't have it (and I never had this in 3.6 so it is definitely 3.7 code).

Finding out the code that is causing this is priority #1.  I haven't bug hunted on it yet (just too tired right now) but I'd buy you lunch if you can find it asap (This goes for anyone who sees this).

![shot-159-174](https://cloud.githubusercontent.com/assets/5543934/13308975/699bdabc-db46-11e5-9dcf-f126581b05ec.png)

**Comment by phrack** [comment]
I strongly believe this is relatively recent because I didn't see it before the major restructuring for masks and I did use 3.7 significantly in that time. I think the best place to start is to try older commits from the last few weeks to see if the corruption is there to find the commit that started it all. Once that's done it should be much easier to find potential causes in the diff.

I likely won't be able to even touch this today.
