### ISSUE TITLE
Color detection is unusually wrong in some scenarios

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#402]
Despite being decent in our tests, it is failing on easy cases in the videos provided by /u/greatone123x

I've made a new test from one of his videos.  Will look into it.

Shot:
![shot-325-245_orig](https://cloud.githubusercontent.com/assets/5543934/13512251/837b2c86-e167-11e5-8dd8-8bacbd9f5621.png)

Detected as:
![shot-325-245](https://cloud.githubusercontent.com/assets/5543934/13512250/837577f0-e167-11e5-860b-390fd5b4d8af.png)

**Comment by phrack** [comment]
I can help test this and maybe try tweaks too. It is wrong about as often as it is right with my projector, I am just rarely using an exercise where it matters. In fact, in most of my uses the color is irrelevant and I don't even look at what they are because I don't show shots on the arena and reset from a target without even looking at my computer.

**Comment by cbdmaul** [comment]
Going to push a patch that should fix this pretty well.

![shot-325-245_orig](https://cloud.githubusercontent.com/assets/5543934/13549470/c6c9f040-e2d3-11e5-9d0a-c878f79b2f5b.png)

![shot-325-245](https://cloud.githubusercontent.com/assets/5543934/13549473/cb57a44a-e2d3-11e5-9352-2b02d481c0cc.png)
