### ISSUE TITLE
Add switch to disable frame delay calculation in autocalibration

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#408]
It appears to fail for at least one user: https://www.reddit.com/r/ShootOFF/comments/49k7ve/autocalibration_help/

We don't use the result anyway, we should add a switch to disable it.

**Comment by phrack** [comment]
I am adding a constant to Configuration that says whether or not this and masking code should be on. I am re-adding back the masking code but I am making it only run if this constant is true (it will be false by default). This way to use the masking code and its dependencies you just change the constant from false to true in the Configuration class. I am not making this accessible outside of changing the code because it doesn't seem like something anyone but someone working on masking code would ever want to change.
