### ISSUE TITLE
Implement a disappearing bouncing targets exercise

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#446]
Display a group of bouncing targets.  Remove targets that are hit.  Reset when there are no more targets.

More info: https://www.reddit.com/r/ShootOFF/comments/4jadgr/bouncing_targets/

**Comment by ifly53e** [comment]
code to make this happen has been inserted at the "mod" comments below.

/*
- ShootOFF - Software for Laser Dry Fire Training
- Copyright (C) 2016 phrack
- 
- This program is free software: you can redistribute it and/or modify
- it under the terms of the GNU General Public License as published by
- the Free Software Foundation, either version 3 of the License, or
- (at your option) any later version.
- 
- This program is distributed in the hope that it will be useful,
- but WITHOUT ANY WARRANTY; without even the implied warranty of
- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
- GNU General Public License for more details.
- 
- You should have received a copy of the GNU General Public License
- along with this program.  If not, see http://www.gnu.org/licenses/.
  */

package com.shootoff.plugins;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.Random;

import javafx.animation.KeyFrame;
import javafx.animation.Timeline;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.geometry.Bounds;
import javafx.geometry.Dimension2D;
import javafx.geometry.HPos;
import javafx.geometry.Point2D;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.Label;
import javafx.scene.layout.ColumnConstraints;
import javafx.scene.layout.GridPane;
import javafx.stage.Modality;
import javafx.stage.Stage;
import javafx.util.Duration;

import com.shootoff.camera.Shot;
import com.shootoff.targets.Hit;
import com.shootoff.targets.Target;

public class BouncingTargets extends ProjectorTrainingExerciseBase implements TrainingExercise {
    private int shootCount = 4;
    private int dontShootCount = 1;
    private static int maxVelocity = 10;
    private boolean disappearingTargets = false;//mod

```
private static final List<BouncingTarget> shootTargets = new ArrayList<BouncingTarget>();
private static final List<BouncingTarget> dontShootTargets = new ArrayList<BouncingTarget>();

private static ProjectorTrainingExerciseBase thisSuper;
private Timeline targetAnimation;
private int score = 0;

private boolean testing = false;

public BouncingTargets() {}

public BouncingTargets(List<Target> targets) {
    super(targets);
    setThisSuper(super.getInstance());
}

// For testing
protected void init(int shootCount, int dontShootCount, int maxVelocity) {
    testing = true;

    this.shootCount = shootCount;
    this.dontShootCount = dontShootCount;
    setMaxVelocity(maxVelocity);

    shootTargets.clear();
    dontShootTargets.clear();

    startExercise();
}

private static void setThisSuper(ProjectorTrainingExerciseBase thisSuper) {
    BouncingTargets.thisSuper = thisSuper;
}

private static void setMaxVelocity(int maxVelocity) {
    BouncingTargets.maxVelocity = maxVelocity;
}

@Override
public void init() {
    collectSettings();

    startExercise();
}

private void startExercise() {
    super.showTextOnFeed("Score: 0");

    addTargets(shootTargets, "targets/shoot_dont_shoot/shoot.target", shootCount);
    addTargets(dontShootTargets, "targets/shoot_dont_shoot/dont_shoot.target", dontShootCount);

    targetAnimation = new Timeline(new KeyFrame(Duration.millis(20), e -> updateTargets()));
    targetAnimation.setCycleCount(Timeline.INDEFINITE);
    targetAnimation.play();
}

private void collectSettings() {
    super.pauseShotDetection(true);

    final Stage bouncingTargetsStage = new Stage();
    final GridPane bouncingTargetsPane = new GridPane();

    final ColumnConstraints cc = new ColumnConstraints(100);
    cc.setHalignment(HPos.CENTER);
    bouncingTargetsPane.getColumnConstraints().addAll(new ColumnConstraints(), cc);

    final int MAX_TARGETS = 10;
    final int MAX_VELOCITY = 30;

    final int SHOOT_DEFAULT_COUNT = 4 - 1;
    final int DONT_SHOOT_DEFAULT_COUNT = 1 - 1;
    final int DEFAULT_MAX_VELOCITY = 10;

    final ObservableList<String> targetCounts = FXCollections.observableArrayList();
    for (int i = 1; i <= MAX_TARGETS; i++)
        targetCounts.add(Integer.toString(i));
    final ComboBox<String> shootTargetsComboBox = new ComboBox<String>(targetCounts);
    shootTargetsComboBox.getSelectionModel().select(SHOOT_DEFAULT_COUNT);
    bouncingTargetsPane.add(new Label("Shoot Targets:"), 0, 0);
    bouncingTargetsPane.add(shootTargetsComboBox, 1, 0);

    final ComboBox<String> dontShootTargetsComboBox = new ComboBox<String>(targetCounts);
    dontShootTargetsComboBox.getSelectionModel().select(DONT_SHOOT_DEFAULT_COUNT);
    bouncingTargetsPane.add(new Label("Don't Shoot Targets:"), 0, 1);
    bouncingTargetsPane.add(dontShootTargetsComboBox, 1, 1);

    final ObservableList<String> maxVelocity = FXCollections.observableArrayList();
    for (int i = 1; i <= MAX_VELOCITY; i++)
        maxVelocity.add(Integer.toString(i));
    final ComboBox<String> maxVelocityComboBox = new ComboBox<String>(maxVelocity);
    maxVelocityComboBox.getSelectionModel().select(DEFAULT_MAX_VELOCITY - 1);
    bouncingTargetsPane.add(new Label("Max Target Speed:"), 0, 2);
    bouncingTargetsPane.add(maxVelocityComboBox, 1, 2);

    //mod
    final ObservableList<String> disappearTargetList = FXCollections.observableArrayList();
    disappearTargetList.add("Yes");
    disappearTargetList.add("No");
    final ComboBox<String> disappearTargetComboBox = new ComboBox<String>(disappearTargetList);
    disappearTargetComboBox.getSelectionModel().select(1);
    bouncingTargetsPane.add(new Label("Targets disappear after hit:"), 0, 3);
    bouncingTargetsPane.add(disappearTargetComboBox, 1, 3);

    final Button okButton = new Button("OK");
    okButton.setDefaultButton(true);
    bouncingTargetsPane.add(okButton, 1, 4);//mod

    okButton.setOnAction((e) -> {
        shootCount = Integer.parseInt(shootTargetsComboBox.getSelectionModel().getSelectedItem());
        dontShootCount = Integer.parseInt(dontShootTargetsComboBox.getSelectionModel().getSelectedItem());
        BouncingTargets.maxVelocity = Integer.parseInt(maxVelocityComboBox.getSelectionModel().getSelectedItem());

        //mod
        if(disappearTargetComboBox.getSelectionModel().getSelectedItem()=="Yes"){
            disappearingTargets = true;
        }else{
            disappearingTargets = false;
        }



        bouncingTargetsStage.close();
    });

    final Scene scene = new Scene(bouncingTargetsPane);
    bouncingTargetsStage.initOwner(super.getShootOFFStage());
    bouncingTargetsStage.initModality(Modality.WINDOW_MODAL);
    bouncingTargetsStage.setTitle("Bouncing Targets Settings");
    bouncingTargetsStage.setScene(scene);
    bouncingTargetsStage.showAndWait();

    super.pauseShotDetection(false);
}

protected List<BouncingTarget> getShootTargets() {
    return shootTargets;
}

protected List<BouncingTarget> getDontShootTargets() {
    return dontShootTargets;
}

private void updateTargets() {
    for (BouncingTarget b : shootTargets)
        b.moveTarget();
    for (BouncingTarget b : dontShootTargets)
        b.moveTarget();
}

protected static class BouncingTarget {
    private final Target target;
    private double dx;
    private double dy;

    public BouncingTarget(Target target) {
        this.target = target;

        Random r = new Random();

        dx = r.nextInt(maxVelocity + 1) + 1;
        dy = r.nextInt(maxVelocity + 1) + 1;

        if (r.nextBoolean()) dx *= -1;
        if (r.nextBoolean()) dy *= -1;
    }

    public Target getTarget() {
        return target;
    }

    private enum CollisionType {
        NONE, COLLISION_X, COLLISION_Y, COLLISION_BOTH;
    }

    private CollisionType checkCollision() {
        final Bounds targetBounds = target.getBoundsInParent();
        List<BouncingTarget> collisionList;

        if (shootTargets.contains(this)) {
            collisionList = shootTargets;
        } else {
            collisionList = dontShootTargets;
        }

        for (BouncingTarget b : collisionList) {
            if (b.getTarget().equals(target)) continue;

            final Bounds bBounds = b.getTarget().getBoundsInParent();

            if (targetBounds.intersects(bBounds)) {
                final boolean atRight = targetBounds.getMaxX() > bBounds.getMinX()
                        && targetBounds.getMaxX() - bBounds.getMinX() < maxVelocity * 2;
                final boolean atLeft = bBounds.getMaxX() > bBounds.getMinX()
                        && bBounds.getMaxX() - bBounds.getMinX() < maxVelocity * 2;
                final boolean atBottom = targetBounds.getMaxY() > bBounds.getMinY()
                        && targetBounds.getMaxY() - bBounds.getMinY() < maxVelocity * 2;
                final boolean atTop = bBounds.getMaxY() > targetBounds.getMinY()
                        && bBounds.getMaxY() - targetBounds.getMinY() < maxVelocity * 2;

                if ((atRight || atLeft) && (atBottom || atTop)) {
                    return CollisionType.COLLISION_BOTH;
                } else if (atRight || atLeft) {
                    return CollisionType.COLLISION_X;
                } else if (atBottom || atTop) {
                    return CollisionType.COLLISION_Y;
                }
            }
        }

        return CollisionType.NONE;
    }

    public void moveTarget() {
        if (maxVelocity == 0) return;

        Bounds b = target.getBoundsInParent();
        Point2D p = target.getPosition();
        Dimension2D d = target.getDimension();
        CollisionType ct = checkCollision();

        if (b.getMinX() <= 1 || b.getMinX() + d.getWidth() > thisSuper.getArenaWidth()
                || ct == CollisionType.COLLISION_X || ct == CollisionType.COLLISION_BOTH) {
            dx *= -1;
        }

        if (b.getMinY() <= 1 || b.getMinY() + d.getHeight() > thisSuper.getArenaHeight()
                || ct == CollisionType.COLLISION_X || ct == CollisionType.COLLISION_BOTH) {
            dy *= -1;
        }

        target.setPosition(p.getX() + dx, p.getY() + dy);
    }
}

private void addTargets(List<BouncingTarget> targets, String target, int count) {
    for (int i = 0; i < count; i++) {
        Optional<Target> newTarget = super.addTarget(new File(target), 0, 0);

        if (newTarget.isPresent()) {
            // Randomly place the target
            int maxX = (int) (super.getArenaWidth() - newTarget.get().getDimension().getWidth() - 50);
            int x = new Random().nextInt(maxX + 1) + 1;

            int maxY = (int) (super.getArenaHeight() - newTarget.get().getDimension().getHeight() - 50);
            int y = new Random().nextInt(maxY + 1) + 1;

            newTarget.get().setPosition(x, y);

            targets.add(new BouncingTarget(newTarget.get()));
        }
    }
}

@Override
public ExerciseMetadata getInfo() {
    return new ExerciseMetadata("Bouncing Targets", "1.0", "phrack with mods by ifly53e",
            "This exercise randomly moves shoot (gray ring) and don't shoot (red ring) targets"
                    + " around the arena. All targets bounce off the arena bounds and targets of the "
                    + "same type can bounce off of each other. Don't shoot targets are always able to "
                    + "overlap shoot targets. This exercise is scored. Your score is the tally of how "
                    + "many shoot targets you have hit since shooting your last don't shoot target.");
}

@Override
public void shotListener(Shot shot, Optional<Hit> hit) {
    if (hit.isPresent()) {
        if (hit.get().getHitRegion().tagExists("subtarget")) {
            switch (hit.get().getHitRegion().getTag("subtarget")) {
            case "shoot": {
                score++;
                super.showTextOnFeed(String.format("Score: %d", score));
                //mod
                if(disappearingTargets){
                    hit.get().getTarget().setVisible(false);
                    if(score==shootCount)reset();
                }

            }
                break;

            case "dont_shoot": {
                super.playSound("sounds/beep.wav");
                TextToSpeech.say(String.format("Your score was %d", score));
                score = 0;
                super.showTextOnFeed("Score: 0");
            }
                break;
            }
        }
    }
}

@Override
public void reset(List<Target> targets) {
    targetAnimation.stop();

    for (BouncingTarget b : shootTargets)
        super.removeTarget(b.getTarget());
    shootTargets.clear();
    for (BouncingTarget b : dontShootTargets)
        super.removeTarget(b.getTarget());
    dontShootTargets.clear();

    if (!testing) collectSettings();

    addTargets(shootTargets, "targets/shoot_dont_shoot/shoot.target", shootCount);
    addTargets(dontShootTargets, "targets/shoot_dont_shoot/dont_shoot.target", dontShootCount);

    targetAnimation.play();

    score = 0;
    super.showTextOnFeed("Score: 0");
}
```

}

**Comment by ifly53e** [comment]
Pull request added

**Comment by cbdmaul** [comment]
Verification of the pull request will have to wait for Phrack's approval, I'm not familiar with the exercise components.  He should be back at it soon.

**Comment by phrack** [comment]
I am back, but will take a few days to get to the pull request. I am still working my way through emails (almost done though) and haven't even looked at the subreddit yet.

**Comment by PrzemekDomka** [comment]
During the tests, bouncing targets2. jar (plugin) I saw a problem with the speed settings. Try setting (10 (speed) dissapear YES, then 1 speed dissapear YES, then 10 dissapear YES) several times. If you set the speed 1 (after setting 10) setting does not work. Speed 1 is faster at first time. Then compare the speed "1" of the original bouncing targets. When you change the speed never restart the program.
(Shootoff 3.8)
Platform:
Linux 3.16.0-4-amd64 Debian Jessie
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

**Comment by ifly53e** [comment]
I could not replicate this problem in my setup...

I did notice that speed setting is a maximum so you can't assume all of the targets will travel at the same speed.

   public BouncingTarget(Target target) {
        this.target = target;

```
    Random r = new Random();

    dx = r.nextInt(maxVelocity + 1) + 1;
    dy = r.nextInt(maxVelocity + 1) + 1;

    if (r.nextBoolean()) dx *= -1;
    if (r.nextBoolean()) dy *= -1;
}
```

The above code takes the maximum velocity setting and makes the x and y change in velocity random numbers between 1 and that setting number.  So if you are expecting to see all of the moving targets move at the same speed when the setting is 10, then that will only happen by random chance.

All of the targets should be moving pretty slow when the setting is 1 so I am not sure why you are seeing major changes in speed at the slowest setting.

**Comment by phrack** [comment]
I have three suggestions at the moment (perhaps more if there is a pull request):
1. The Yes/No setting for making targets disappear should probably just be a checkbox instead of a dropdown list and a label. Unless, of course, there is some good reason for it to not be a checkbox.
2. Targets should be removed when "disappeared" instead of making them invisible. If they are removed they don't need to be processed under the hood anymore. Also, a shot on an invisible target can still be detected as a hit. We have several targets with shootable regions with their visibility set to false.
3. This change is a combination of simple enough and useful enough to just incorporate in the official version instead of having a "Bouncing Targets 2" IMO.

**Comment by ifly53e** [comment]
Phrack,
1.  Small dog to puppy...not consistent with previous shootOff exercises.  Personal preference and it is your project.  Overkill...yes, but it is done.
2.  If the targets are not drawn in the scene, how can they be hit?  I realize they are still being moved under the hood but that is a small performance hit compared to the search you are going to have to do to find the Target, compare it to the bouncingTarget, and then remove the bouncingTarget from the list all during the shotDetection algorithm.  That is more code to implement than the one liner to make the target invisible.  But, I would like to see how you would do that since I was not about to invest the time for a change I knew you would probably not accept in the first place.
3. I am not a core developer so I would never get that change with a pull request anyway so learning how to complete and compile a module and submitting the pull request according to the rules you put forth in the tutorial was my only option.

I hope that ksorken got some use out of it while he was waiting for Phrack to get to this.

Welcome back, Phrack. 

I missed you.

Love, Ifly53e

**Comment by phrack** [comment]
My point about 2 is that the request seems to be asking that the exercise reset once each shoot target is shot at least once (disappearing just being a nice way to know which ones have been shot and to remove distractions). That is not what is implemented. An invisible target can still be shot because it's still in the list and the hit detection algorithm doesn't take the visibility of the JavaFX node into account (https://github.com/phrack/ShootOFF/blob/master/src/main/java/com/shootoff/gui/TargetView.java#L409), only if the target is in the list + the top most target + with a shot in one of its region's bounds (if it's an image region the shot can't be on a pixel whose alpha value makes it invisible -- not the same as JavaFX node visibility). With what's implemented you can hit a shoot target multiple times and the exercise will reset even though you haven't shot each of them once because `score==shootCount`. I shouldn't have brought up efficiency because you're right that it's a red herring when the point is really about correctness. Maybe I am interpreting the request wrong though.

We do accept pull requests from non-core developers and have many times. Yours rarely get accepted  (or so far have never been?) because you seemingly refuse to make corrections to remain consistent with the rest of ShootOFF, make even small quality improvements, etc. The GUI point is a good example: no where else in ShootOFF is a dropdown list used to graphically represent a boolean value. In all cases where a dropdown list is used it's because there is no better way to graphically reflect the input. The speeds for example have to be bounded (e.g. 1 - 10), a text box isn't great for this in this case because the space of possible speeds it not very big and documenting what freeform inputs are actually valid would be burdensome to us and users. 

I am not picking on you. I wish we had enough developers that I could be reviewed too. Even half of my commits would be rejected on the first try because, just like proof reading prose, it's very hard to spot even some obvious bugs in your own code unless you haven't touched it in a few weeks. This would save us a lot of bugs.

**Comment by phrack** [comment]
Seriously, on the review point: filter our closed issued by bugs. There are 209 closed bugs. It's a safe bet that this number would be cut in half or more if we had enough developers all along that even the core developers were getting reviewed and rejected.
