### ISSUE TITLE
Paper pattern is not discovered when full pattern causes camera exposure to change

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#481]

**Comment by cbdmaul** [comment]
I have committed something that works with tests but I have no projector to test with at my current location.

**Comment by phrack** [comment]
I can try to fix this. So far, aside from this exception, it has been working very well.

Exception in thread "ShotDetector" java.util.NoSuchElementException: No value present
    at java.util.Optional.get(Optional.java:135)
    at com.shootoff.camera.autocalibration.AutoCalibrationManager.findPatterns(AutoCalibrationManager.java:344)
    at com.shootoff.camera.autocalibration.AutoCalibrationManager.stepOne(AutoCalibrationManager.java:303)
    at com.shootoff.camera.autocalibration.AutoCalibrationManager.processFrame(AutoCalibrationManager.java:214)

**Comment by phrack** [comment]
I'll actually have to leave that exception to you because my attempts to fix it (just adding a break or a continue if it wasn't present) seemed to hopeless break things.

It was working in conditions like this:

![paper_detection_lighting](https://cloud.githubusercontent.com/assets/174818/17084149/c4010b26-5184-11e6-8d30-c5af85d4cdce.png)

This seemed to be the first breaking point, but I don't think it's even fair since you can't really see the pattern in any condition:

![breaking_point](https://cloud.githubusercontent.com/assets/174818/17084155/db6ae0ac-5184-11e6-88b2-b6c7e8991f03.png)

In addition to that exception, which became quite frequent the more I tested, the most common problem was that the frame would get stuck in some intermediate state when it would try to find the pattern, then obviously it never found the pattern. Here is an example where the message telling you that you need to calibrate never quite went away:

![calibration_staying](https://cloud.githubusercontent.com/assets/174818/17084163/ffd3d606-5184-11e6-954e-e9977c0283b9.png)

I got a bunch of different variations of this including the arena not being all the way up yet, the arena being up but the pattern not being up yet, etc. These aren't problems with the GUI, it's just that things were still in a state of flux by the time ACM started to look for the pattern and bogged everything down. If it had delayed just a tiny bit longer it probably would have worked.

**Comment by phrack** [comment]
I am also getting mask-0..3.png dumped to the file system.

**Comment by cbdmaul** [comment]
I know what the problems are, working on a fix.

**Comment by phrack** [comment]
I knew that would be the case, thus I still have everything set up for when you give me a thumbs up to test again.

**Comment by cbdmaul** [comment]
Should be fixed now.  Your paper pattern is upside down (which doesn't matter, we just don't have a test for that).

As for the ACM starting too quickly, seems like that should be on the manager's side and not acm's problem, if i'm understanding the issue correctly

**Comment by phrack** [comment]
I think the ACM starting too quickly issue was actually due to the exception and my non-solutions to it. I can't dupe it anymore even in the same lighting conditions. In fact, it's working very well now even in conditions it didn't before.

**Comment by phrack** [comment]
PS. I think it's safe to say there is no upside down because it's been working fine for me all day that way. Working on the CFDA exercise.

**Comment by cbdmaul** [comment]
I added logic to sort the corners.  It was already written previously but I didn't use it because I thought going between matofpoint and point[] was too difficult.  I know more about opencv now, enough to know there are toarray/fromarray functions...
