### ISSUE TITLE
Auto-adjust camera settings to improve accuracy for the user

### ISSUE THREAD

**Issue by phrack** [phrack/ShootOFF#504]
Adjusting just the exposure down slowly should deal with both bad lighting and motion to some degree.

**Comment by cbdmaul** [comment]
This should have been mentioned in my commits, but the logic for this is now in #543

**Comment by cbdmaul** [comment]
I think before closing this, we should add a preference option to disable it.  Just in case it does end up hosing somebody's exposure settings.  I think it is good enough to have autocalibration check to see if it is disabled and not attempt it, since that's the only place the functions in Camera are called from right now.

Maybe we want to have some kind of long notification message on the camera feed to notify the user that the exposure was lowered and that they should use the arena tab to make arena changes, so that we don't get users confused by the darkness of the feed.

One last thought is that the exposure should be changed back in most non-calibrated non-detecting situations so that the user can make adjustments due to camera misalignment and so on.  This is more about going through the code and making sure that it is reset at appropriate times and then a bit of testing to confirm.
