### ISSUE TITLE
Data added to training exercise column in the shot timer intermittently doesn't show immediate on Windows

### ISSUE THREAD

**Issue by phrack** [phrack/ShootOFF#505]
Start Shoot for Score and hit the target several times. Sometimes the score column's data won't show until another entry is added.

**Comment by cbdmaul** [comment]
It might have something to do with the dedupe changes.  The reset bug was due to the dedupe processor not being reset, leading to there being a "lastShot" that was very far in the future.  This is because shots are stored with a relative time to the last restart.  There could also be threading issues here, lots of moving parts related to timestamps...
