### ISSUE TITLE
Error when shot list exceeds height (Scrollbar added)

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#530]
Sep 02, 2016 11:15:27 PM com.sun.javafx.scene.control.skin.VirtualFlow addTrailingCells
INFO: index exceeds maxCellCount. Check size calculations for class com.shootoff.gui.controller.ShootOFFController$3

**Comment by phrack** [comment]
This is a known JavaFX issue with no resolution when auto-scrolling because the software scrolls faster than a human. It doesn't cause an actual issue and has been around since we moved to JavaFX, thus it's not worth spending more time on.

The log message is only encountered in debug mode because we set the log level to WARN otherwise.
