### ISSUE TITLE
Various bugs with prospective gui

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#535]
1. Perspective panel does not go away if target is deleted
2. Changing the target width makes the target tiny.  Changing the height fixes it again.

**Comment by phrack** [comment]
Regarding 2. The GUI doesn't appear to do anything that would mix up or return the wrong values. Aside from new validation code (to validate on the fly), almost all of the code is the same as it was before since it's visual changes. You could put com.shootoff.gui.pane.TargetDistancePane in trace and see what this message says: "New target settings from distance settings pane: current width...".

If it all looks correct, it's definitely not the GUI.

**Comment by phrack** [comment]
- [x] Target deleted using mouse
- [x] Target deleted using CanvasManage.clearTargets()
