### ISSUE TITLE
Shot To Click leaves visible mouse cursor

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#558]
Ideally, Shot To Click either uses an invisible cursor or moves the cursor off screen after clicking

Don't know if this is only Windows behavior or if it's come up before.

**Comment by phrack** [comment]
I don't think any window system gives you control over what the cursor looks like on someone elses window. We're lucky they even let us move it over a window that isn't ours and click.

If we filtered exercises by capabilities. Shot to click would firmly be on my IR + filter list.

**Comment by cbdmaul** [comment]
Well that's why I mentioned just moving it out of the way after clicking.

**Comment by phrack** [comment]
Seems like it'd be a simple update to just move the mouse back to where it was before automatically moving it. This, in theory, would cause the mouse to move around all over the place, but always go back to where the user left it when they started. I suggest trying that since you can actually test it (I can release the new version if it works). I honestly was never all that confident this exercise even worked decently since it causes so many motion issues I could never comfortably test it in the actual use case (playing a game).

**Comment by cbdmaul** [comment]
Moved to proper repo
