### ISSUE TITLE
Perspective requires changing a parameter to work despite having all needed settings

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#627]

**Comment by phrack** [comment]
The resize to default method is being called when a target is added:

https://github.com/phrack/ShootOFF/blob/master/src/main/java/com/shootoff/gui/pane/ProjectorArenaPane.java#L609
https://github.com/phrack/ShootOFF/blob/master/src/main/java/com/shootoff/gui/pane/ProjectorArenaPane.java#L682

I see two oddities at the moment. This should use `isInitialized` otherwise we have to keep track of what the required paramters for the perspective to be "initialized" are in multiple places:

https://github.com/phrack/ShootOFF/blob/master/src/main/java/com/shootoff/gui/pane/ProjectorArenaPane.java#L682

The error log when it is not initialized should dump the values so that the log shows exactly what isn't initialized.

My only other thought at the moment is that resizing when a target is added was only tested when we calibrated with paper. When we did this test yesterday we didn't use the paper, thus it could be related to that (i.e. something might not be getting initialized correctly later if the paper wasn't detected).
