### ISSUE TITLE
checkhit called twice for each shot

### ISSUE THREAD

**Issue by ifly53e** [phrack/ShootOFF#638]
CanvasManager calls checkhit here from addShot:
https://github.com/phrack/ShootOFF/blob/master/src/main/java/com/shootoff/gui/CanvasManager.java#L588

Inside addShot, addArenaShot is called and checkhit is called again.

https://github.com/phrack/ShootOFF/blob/master/src/main/java/com/shootoff/gui/CanvasManager.java#L604

https://github.com/phrack/ShootOFF/blob/master/src/main/java/com/shootoff/gui/CanvasManager.java#L627

It appears work is being done on the same shot twice...can this be more efficient?   For me, the first call to checkhit rarely (if ever) returned a hit, but the second call did return a hit.

**Comment by phrack** [comment]
More precisely, it's called twice for each shot that falls on a calibrated region. Once to check for a hit on the webcam feed's canvas and a second time to check for hits on the arena window's canvas. Not literally for each shot.

I don't recall a specific reason for this behavior, thus it probably does make sense to modify that logic to only call check hit for the webcam feed's canvas if we aren't going to pass the shot to the arena's canvas.

PS. This doesn't really cause a performance hit because most people don't add targets to the webcam feed when it's calibrated thus the first check will bail out essentially instantly anyway. That doesn't mean the code can't be refactored to be more clear anyway.
