### ISSUE TITLE
Shot times end up negative

### ISSUE THREAD

**Issue by phrack** [phrack/ShootOFF#641]
![screenshot from 2016-10-23 10-46-21](https://cloud.githubusercontent.com/assets/174818/19627133/03afc9e4-990e-11e6-99ef-c498ba05e959.png)

The first shot with a time of -0.01 is a real shot I made with a laser pointer. The shots with times that are large negative numbers are click to shoot shots. I am assuming this is related to changes for the OptiTrack time stamps.

**Comment by cbdmaul** [comment]
The problem is that an epoch time is maintained in CameraManager but the shot detectors return a full timestamp.  See cameraTimeToShotTime

I tried to make CameraManager handle that but I guess I failed.  The -0.01 makes sense (as a bug), if the system is slow, resetting the epoch will result in a time slightly slower than the initial shot.  The huge negative ones, I don't know.

**Comment by phrack** [comment]
I'd be OK closing this with just the -0.01 fixed since regular users will see that. Click to shot timestamps (the large negative ones) would be nice to fix eventually, but it doesn't hurt anything that I can think of.

**Comment by cbdmaul** [comment]
In that case, all that needs to happen is make the reset take a timestamp parameter and set that as the epoch

**Comment by phrack** [comment]
I am confused by the reset part because this happens even if there never was a reset. I consistently get it for the first shot after opening ShootOFF.

**Comment by cbdmaul** [comment]
the epoch has to be set every time there is a first shot
