### ISSUE TITLE
Camera names with colons cause webcamInternalNames to be wrong for subsequent starts

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#658]
Line 284 Configuration.java

**Comment by phrack** [comment]
The problem is that in the properties file cameras are stored in the following format:

User Defined Name:System Defined Name

If there is a colon in either name when ShootOFF splits the string by a colon it gets the wrong camera names. For example with the string:

`UVC Camera (046d\:0825) /dev/video1\:UVC Camera (046d\:0825) /dev/video1`

It ends up thinking the user defined name is `UVC Camera (046d` and the system defined name is `0825) /dev/video1`.
