### ISSUE TITLE
Use the first non-busy camera as the default rather than failing if the first camera is busy

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#659]
CameraFactory, line 100, getDefault()

We use Webcam.getDefault(), then addConfiguredCameras in ShootOFFController.java attempts to use this camera.  If it fails, ShootOFF exits.

Modify getDefault to use an index approach and iterate the available cams until ShootOFFController is satisfied or gives up.

**Comment by phrack** [comment]
The problem is that at some point you (according to blame: https://github.com/phrack/ShootOFF/blame/master/src/main/java/com/shootoff/camera/CameraManager.java#L187) made the `CameraManager`'s start method show the error about a locking issue. This overrides the `ShootOFFController`'s attempts to fall back to a different camera, but the code IS there to fall back to a different camera. I've cleaned up some of that code while working towards trying to trickle this error back up the call stack instead of showing the error from the `CameraManager`
