### ISSUE TITLE
ShootOFF-diagnostics Crashes

### ISSUE THREAD

**Issue by benito334** [phrack/ShootOFF#707]
ShootOFF (both 4.0 Final & 3.1 Final) runs fine on Windows10 Pro 64x with clean Java (v8 Update 144 build 1.8.0_144-b01) install. When I try to run ShootOFF-diagnostics it opens but then crashes after a few seconds. 
[shootoff-diagnostics.log](https://github.com/phrack/ShootOFF/files/1405339/shootoff-diagnostics.log)

**Comment by phrack** [comment]
Do you have a ps3eye connected? If so, you need to follow these instructions to get rid of the ps3eye errors:

https://github.com/phrack/ShootOFF/wiki/PS3Eye

If not, the other errors in the log are ignorable. They occur because we no longer have remote error reporting servers and we haven't removed the client code yet (doesn't prevent ShootOFF from working so not a high priority).

Finally, the diagnostic tool is supposed to shut ShootOFF down after 15 seconds. The diagnostic tool is meant to help people debug start-up problems. We added the automatic shutdown after 15 seconds because some people had start-up problems that caused ShootOFF's Java process to continue to silently live in the background and we wanted to clean up the "garbage".
